name: OBBX Hybrid Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore Dependencies
      run: dotnet restore OBBX.sln
    - name: Build Web Project
      run: dotnet build "OBBX\OBBX.Web\OBBX.Web.csproj" -c Release

    - name: Publish Web App
      run: dotnet publish "OBBX\OBBX.Web\OBBX.Web.csproj" -c Release -o ./web-publish

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OBBX-Web-TestBuild
        path: ./web-publish